---

- name: install podman
  package:
   name: podman
   state: latest

- name: create podman directories
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - /home/var/lib/containers/storage
    - /home/var/run/containers/storage

- name: change podman temporary storage location
  lineinfile:
    line: 'runroot = "/home/var/run/containers/storage"'
    regexp: 'runroot = ".+"'
    path: /etc/containers/storage.conf
    state: present
    backup: yes

- name: change podman primary R/W location
  lineinfile:
    line: 'graphroot = "/home/var/lib/containers/storage"'
    regexp: 'graphroot = ".+"'
    path: /etc/containers/storage.conf
    state: present
    backup: yes

- name: install semanage
  become: yes
  package:
    name: policycoreutils-python-utils
    state: present

- name: change SELinux labels
  when: ansible_selinux is defined and ansible_selinux != False and ansible_selinux.status == 'enabled'
  become: yes
  community.general.sefcontext:
    target: '/home/var/lib/containers(/.*)?'
    seuser: system_u
    setype: lib_t
    selevel: s0
    state: present

- name: apply new SELinux file context to filesystem
  become: yes
  ansible.builtin.command: restorecon -irv /home/var/lib/containers
