---

- name: ensuring a checkout of assisted-test-infra exists
  git:
    repo: 'https://github.com/openshift/assisted-test-infra.git'
    dest: /home/test/assisted-test-infra
    update: no

- name: configure environment
  make:
    chdir: /home/test/assisted-test-infra
    target: setup

- name: build image
  make:
    chdir: /home/test/assisted-test-infra
    target: image_build

- name: install xinet
  package:
    name: xinetd
    state: present

- name: start firewalld
  service:
    name: firewalld
    state: started

- name: fetch pull-secret (if exists)
  shell:
    cmd: "cat ~/.ssh/authorized_keys | grep pull-secret | cut -d' ' -f 2 | base64 -d || true"
  register: pull_secret

- name: export PULL_SECRET variable
  when: pull_secret.stdout != ""
  lineinfile:
    line: "export PULL_SECRET='{{ pull_secret.stdout }}'"
    regexp: 'export PULL_SECRET=.+'
    path: "~/.bashrc"
    state: present

- name: configure SSH login for test-infra VMs
  blockinfile:
    path: ~/.ssh/config
    block: |
      Host *test-infra*
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        User core

    state: present
    create: yes
